/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Logic.Controller.KategoriIslemleri;
import Logic.Controller.MarkaIslemleri;
import Logic.Controller.UrunIslemleri;
import Logic.Model.kategori;
import Logic.Model.marka;
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class urunEkrani extends javax.swing.JFrame {

    /**
     * Creates new form urun
     */
    public urunEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        urunEkle = new javax.swing.JButton();
        urunNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        yeniSifre = new javax.swing.JLabel();
        sifreTekrari = new javax.swing.JLabel();
        sifreTekrari1 = new javax.swing.JLabel();
        urunFiyat = new javax.swing.JTextField();
        sifreTekrari2 = new javax.swing.JLabel();
        marka = new javax.swing.JComboBox<>();
        kategori = new javax.swing.JComboBox<>();
        markaAdi = new javax.swing.JLabel();
        kategoriAdi = new javax.swing.JLabel();
        yeniKategori = new javax.swing.JTextField();
        yeniMarka = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        urunadi = new javax.swing.JTextField();
        kategoriArtir = new javax.swing.JLabel();
        markaArtir = new javax.swing.JLabel();
        urunadedi = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(190, 140, 110));

        jLabel2.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ürün Ekleme");

        urunEkle.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        urunEkle.setText("Ürün Ekle");
        urunEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunEkleActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jLabel3.setText("Ürün No :");

        jLabel4.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jLabel4.setText("Ürün Adı :");

        yeniSifre.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        yeniSifre.setText("Kategori :");

        sifreTekrari.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        sifreTekrari.setText("Ürün Adedi :");

        sifreTekrari1.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        sifreTekrari1.setText("Ürün Fiyatı :");

        sifreTekrari2.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        sifreTekrari2.setText("Marka :");

        marka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eti", "Ülker", "" }));
        marka.setSelectedIndex(-1);
        marka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                markaKeyReleased(evt);
            }
        });

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tatlı", "Tuzlu" }));
        kategori.setSelectedIndex(-1);
        kategori.setToolTipText("");
        kategori.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kategoriKeyReleased(evt);
            }
        });

        markaAdi.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        markaAdi.setText("Marka Adı :");

        kategoriAdi.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        kategoriAdi.setText("Kategori Adı :");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ürün No", "Ürün Adı", "Kategorisi", "Markası", "Ürün Adedi"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        kategoriArtir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kategoriArtir.setText("+");
        kategoriArtir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kategoriArtirMouseClicked(evt);
            }
        });

        markaArtir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        markaArtir.setText("+");
        markaArtir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                markaArtirMouseClicked(evt);
            }
        });

        urunadedi.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(sifreTekrari)
                                .addGap(18, 18, 18)
                                .addComponent(urunadedi)
                                .addGap(74, 74, 74)
                                .addComponent(sifreTekrari1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(markaAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sifreTekrari2))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(urunNo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(marka, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(yeniMarka))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(markaArtir)
                                        .addGap(51, 51, 51)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(yeniSifre, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(kategoriAdi, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(urunFiyat)
                            .addComponent(yeniKategori)
                            .addComponent(kategori, 0, 120, Short.MAX_VALUE)
                            .addComponent(urunadi))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kategoriArtir)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(urunEkle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urunNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(urunadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifreTekrari2)
                    .addComponent(marka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yeniSifre)
                    .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kategoriArtir)
                    .addComponent(markaArtir))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markaAdi)
                    .addComponent(kategoriAdi)
                    .addComponent(yeniKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yeniMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifreTekrari)
                    .addComponent(sifreTekrari1)
                    .addComponent(urunFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urunadedi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(urunEkle)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
              
    private void urunEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunEkleActionPerformed
        Logic.Model.urun u=new Logic.Model.urun();
        u.setUrunNo(Integer.parseInt(urunNo.getText()));
        u.setUrunAdi(urunadi.getText());
        u.setUrunKategorisi(marka.getSelectedItem().toString());
        u.setUrunAdedi(Integer.parseInt(urunadedi.getText()));
        u.setFiyat(Integer.parseInt(urunFiyat.getText()));
        new UrunIslemleri().urunEkle(u);
        jTable2.setModel(new UrunIslemleri().urunAdiGetir());
                
    }//GEN-LAST:event_urunEkleActionPerformed

    private void markaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_markaKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(yeniMarka.getText().trim().equals(""))
                 JOptionPane.showMessageDialog(null,"Bu alan boş bırakılamaz");
            else{
            marka mrk = new marka();
            mrk.setMarkaAdi(yeniMarka.getText());
            new MarkaIslemleri().markaEkle(mrk);
            }
            marka.removeAllItems();
            String[] markalar = new MarkaIslemleri().markaGetir();
        for(int i=0;i<markalar.length;i++){
            marka.addItem(markalar[i]);
        }
        marka.setSelectedItem(null);
        yeniMarka.setText("");
            
        }
    }//GEN-LAST:event_markaKeyReleased

    private void kategoriKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kategoriKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             if(yeniKategori.getText().trim().equals(""))
                 JOptionPane.showMessageDialog(null,"Bu alan boş bırakılamaz");
            else{
            kategori kat = new kategori();
            kat.setKategoriAdi(yeniKategori.getText());
            new KategoriIslemleri().kategoriEkle(kat);
            }
            kategori.removeAllItems();
            String[] kategoriler = new KategoriIslemleri().kategoriGetir();
        for(int i=0;i<kategoriler.length;i++){
            kategori.addItem(kategoriler[i]);
        }
        kategori.setSelectedItem(null);
            yeniKategori.setText("");
        }
    }//GEN-LAST:event_kategoriKeyReleased

    private void kategoriArtirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kategoriArtirMouseClicked
        if(kategoriArtir.getText().equals("+"))
        {
            yeniKategori.setVisible(true);
            kategoriAdi.setVisible(true);
            kategoriArtir.setText("-");
        }
        else if(kategoriArtir.getText().equals("-"))
        {
            yeniKategori.setVisible(false);
            kategoriAdi.setVisible(false);
            kategoriArtir.setText("+");
        }
    }//GEN-LAST:event_kategoriArtirMouseClicked

    private void markaArtirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_markaArtirMouseClicked
        if(markaArtir.getText().equals("+"))
        {
            markaAdi.setVisible(true);
            markaArtir.setText("-");
        }
        else if(markaArtir.getText().equals("-"))
        {
            markaAdi.setVisible(false);
            markaArtir.setText("+");
        }
    }//GEN-LAST:event_markaArtirMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        String[] markalar = new MarkaIslemleri().markaGetir();
        for(int i=0;i<markalar.length;i++){
            marka.addItem(markalar[i]);
        }
        marka.setSelectedItem(null);
        String[] kategoriler = new KategoriIslemleri().kategoriGetir();
        for(int i=0;i<kategoriler.length;i++){
            kategori.addItem(kategoriler[i]);
        }
        kategori.setSelectedItem(null);
        
        jTable2.setModel(new UrunIslemleri().urunAdiGetir());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(urunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(urunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(urunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(urunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new urunEkrani().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JLabel kategoriAdi;
    private javax.swing.JLabel kategoriArtir;
    private javax.swing.JComboBox<String> marka;
    private javax.swing.JLabel markaAdi;
    private javax.swing.JLabel markaArtir;
    private javax.swing.JLabel sifreTekrari;
    private javax.swing.JLabel sifreTekrari1;
    private javax.swing.JLabel sifreTekrari2;
    private javax.swing.JButton urunEkle;
    private javax.swing.JTextField urunFiyat;
    private javax.swing.JTextField urunNo;
    private javax.swing.JTextField urunadedi;
    private javax.swing.JTextField urunadi;
    private javax.swing.JTextField yeniKategori;
    private javax.swing.JTextField yeniMarka;
    private javax.swing.JLabel yeniSifre;
    // End of variables declaration//GEN-END:variables
}
